name: Node.js CI

on:
  push:
    branches: [main]

env:
  APP_NAME: my-node-app
  NODE_VERSION: 20
  APP_ENV: Prod

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_ENV: development

    steps:
      - name: Build application
        run: 'echo "Environment: $APP_ENV"'

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: 'echo "Environment: $APP_ENV"'
