name: Context Demo

on: push

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show repository
        run: echo "${{ github.repository }}"

      - name: Show branch
        run: echo "${{ github.ref_name }}"
