name: Node.js CI

on:
  push:
    branches: [main]

env:
  APP_NAME: my-node-app
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display variables
        run: |
          echo "App: $APP_NAME"
          echo "Node version: $NODE_VERSION"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Display variables
        run: |
          echo "App: $APP_NAME"
